#!/usr/bin/env python2

import json
from subprocess import call

def main():
    set_hostname()

def set_hostname():
    with open('/mnt/openstack/latest/meta_data.json') as meta:
        data = json.load(meta)
    call(['hostnamectl', 'set-hostname', data['hostname']])

if __name__ == '__main__':
    main()
